# Generated by Django 3.1.7 on 2021-03-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('unique_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_birthdate', models.DateField(blank=True)),
                ('user_position', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_avatar', models.ImageField(blank=True, upload_to='')),
                ('user_project', models.ManyToManyField(blank=True, to='tasks.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_theme', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=100)),
                ('task_start_date', models.DateTimeField(blank=True)),
                ('task_end_date', models.DateTimeField(blank=True)),
                ('task_type', models.CharField(choices=[('b', 'Bug'), ('f', 'Feature')], default='f', max_length=1)),
                ('task_priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('task_estimation_hours', models.IntegerField()),
                ('task_creator', models.ForeignKey(on_delete=models.SET('user_deleted'), related_name='user_task_creator', to='tasks.users')),
                ('task_developer', models.ForeignKey(blank=True, on_delete=models.SET('user_deleted'), related_name='user_task_developer', to='tasks.users')),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_spent_time', models.FloatField()),
                ('log_comment', models.CharField(max_length=100)),
                ('log_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
                ('log_user', models.ForeignKey(on_delete=models.SET('user deleted'), to='tasks.users')),
            ],
        ),
    ]
