# Generated by Django 3.1.7 on 2021-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210305_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('user_deleted'), related_name='user_task_developer', to='tasks.users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_project',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Projects'),
        ),
    ]
